PMWelfare/Models/MonthlySummary.cs
namespace PMWelfare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class MonthlySummary
    {
        public int Id { get; set; }

        [Display(Name = "End of Month")]
        public DateTime? EndDate { get; set; }

        [Column(TypeName = "money")]
        [Display(Name = "Closing Balance")]
        public decimal ClosingBalance { get; set; }
    }
}

PMWelfare/Controllers/MonthlySummaryController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMWelfare.Models;

namespace PMWelfare.Controllers

{
    public class MonthlySummaryController : Controller
    {
        private welfare db = new welfare();
        // GET: MonthlySummary

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Closing()
        {
            decimal ClosingBalance = db.Monthlysummary
                 .Where(s => s.EndDate.Value.Month == DateTime.Now.Month - 1
             && s.EndDate.Value.Year == DateTime.Now.Year).Select(s => s.ClosingBalance).FirstOrDefault();

            ViewBag.balance = ClosingBalance;
            return View(ViewBag.balance);
        }
    }
}

PMWelfare/Views/MonthlySummary/Closing.cshtml
@{
    Layout = null;
}
Shs: @ViewBag.balance.ToString("n0")

PMWelfare/Views/MonthlySummary/Index.cshtml
@model IEnumerable<PMWelfare.Models.Subscription>


@{
    ViewBag.Title = "Summery Page";
}
<div>
    <ol class="breadcrumb">
        <li> @Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active"> @Html.ActionLink("Monthly Summary", "Index", "MonthlySummary")</li>
        
    </ol>
</div>
<h1 style="text-align:center">PM-Welfare summary page</h1><br /><br />

<iframe src=""
        frameborder="0" allowTransparency="true"
        style=" float:right;width:60%; height:50em;" name="Details">
    
</iframe>
<div style="width:40%">
    <h2 style="text-align:center">
        Current Ledger of
        @String.Format("{0:MMMM,yyyy}", DateTime.Now)
    </h2><br /><br />
    <h3>At @DateTime.Now</h3>

    <table class="table">
        <tr style="background-color:#999999">
            <th>Particulars</th>
            <th> Total Value</th>
            <th></th>
        </tr>
        <tr class="info">
            <td> Cash At Hand</td>
            <td>@{Html.RenderAction("CashAtHand", "Deposits");}</td>
            <th></th>
        </tr>
        <tr>
            <td>Total Collections</td>
            <td>@{Html.RenderAction("TotalCollection", "Deposits");}</td>
            <td>
                @Html.ActionLink("Details", "../Deposits/Index",
   null, new { target = "Details" })
            </td>
        </tr>
        <tr class="info">
            <td>Advance Collections</td>
            <td>@{Html.RenderAction("Advances", "Subscriptions");}</td>
            <td>
                @Html.ActionLink("Details", "../subscriptions/AdvanceList",
   null, new { target = "Details" })
            </td>
        </tr>
        <tr class="danger">
            <td>Arrears</td>
            <td>
                @{Html.RenderAction("TotalArrears",
                "Subscriptions");}
            </td>
            <td>
                @Html.ActionLink("Details", "../Subscriptions/Arrears",
   null, new { target = "Details" })
            </td>

        </tr >
        <tr class="success">
            <td>Total Expenditure</td>
            <td>@{Html.RenderAction("TotalExpense", "Expenses");}</td>
            <td>
                @Html.ActionLink("Details", "../Expenses/CurrentExpenses",
   null, new { target = "Details" })
            </td>
        </tr>
        <tr>
            <td>Events of the month </td>
            <td>
                @{Html.RenderAction("TotalUpComingEvents",
                "Celebrations");}
            </td>
            <td>
                @Html.ActionLink("Details", "../Celebrations/UpcomingEvents",
   null, new { target = "Details" })
            </td>

        </tr>


    </table>

</div>




<div style="width:40%">
    <h2 style="text-align:center">
        Summary of
        @String.Format("{0:MMMM}", DateTime.Now.AddMonths(-1))
    </h2><br /><br />


    <table class="table" >
        <tr style="background-color:#dfdfdf;background-color:#999999">
            <th>Particulars</th>
            <th> Amount</th>
            <th></th>
        </tr>
        <tr class="info">
            <td> Closing balance</td>
            <td>@{Html.RenderAction("Closing", "MonthlySummary");}</td>
            <td></td>
        </tr>
        <tr>
            <td>Total Expenditure</td>
            <td>@{Html.RenderAction("TotalPreviousMonthExpense", "Expenses");}</td>
            <td>
                @Html.ActionLink("Details", "../expenses/previousmonthexpense",
              null, new { target="Details"})
            </td>
        </tr>
        <tr class="info">
            <td>Total no of events </td>
            <td>
                @{Html.RenderAction("TotaleventsOfPreviousMonth",
                            "Celebrations");}
            </td>
            <td>
                @Html.ActionLink("Details", "../Celebrations/EventsOfPreviousmonth",
              null, new { target="Details"})
            </td>

        </tr>

    </table>

</div>