PMWelfare/Models/SupProducts.cs
namespace PMWelfare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class SupProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupProducts()
        {
            Expenses = new HashSet<Expense>();
        }

        [Key]
        public int ProductId { get; set; }

        [Required]
        [StringLength(40)]
        public string ProductName { get; set; }

        [DisplayFormat(DataFormatString = "Shs:{0:N0}")]
        [Column(TypeName = "money")]
        public decimal? UnitPrice { get; set; }

        
        public int? EventId { get; set; }

        public int? SupId { get; set; }
        
        [StringLength(40)]
        public string CreatedBy { get; set; }

        public DateTime? CreatedAt { get; set; }

        [StringLength(40)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public virtual Celebration Celebration { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expense> Expenses { get; set; }

        public virtual Supplier Supplier { get; set; }
    }
}

PMWelfare/Controllers/SupProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PMWelfare.Models;

namespace PMWelfare.Controllers
{
    public class SupProductsController : Controller
    {
        private welfare db = new welfare();

        // GET: SupProducts
        public ActionResult Index()
        {
            var supProducts = db.SupProducts.Include(s => s.Celebration).Include(s => s.Supplier);
            return View(supProducts.ToList());
        }

        // GET: SupProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupProducts supProducts = db.SupProducts.Find(id);
            if (supProducts == null)
            {
                return HttpNotFound();
            }
            return View(supProducts);
        }

        // GET: SupProducts/Create
        public ActionResult Create()
        {
            ViewBag.EventId = new SelectList(db.Celebrations, 
                "EventId", "EventName");
            ViewBag.SupId = new SelectList(db.Suppliers, 
                "SupId", "SupName");
            return View();
        }

        // POST: SupProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId," +
            "ProductName," +
            "UnitPrice,EventId,SupId,CreatedBy," +
            "CreatedAt,UpdatedBy,UpdatedAt")] SupProducts supProducts)
        {
            supProducts.CreatedAt = DateTime.Now;
            supProducts.CreatedBy = "nicho";
            if (ModelState.IsValid)
            {
                db.SupProducts.Add(supProducts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EventId = new SelectList(db.Celebrations, "EventId", "EventName", 
                supProducts.EventId);
            ViewBag.SupId = new SelectList(db.Suppliers, "SupId", "SupTel",
                supProducts.SupId);
            return View(supProducts);
        }

        // GET: SupProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupProducts supProducts = db.SupProducts.Find(id);
            if (supProducts == null)
            {
                return HttpNotFound();
            }
            ViewBag.EventId = new SelectList(db.Celebrations, "EventId",
                "EventName",
                supProducts.EventId);
            ViewBag.SupId = new SelectList(db.Suppliers, "SupId",
                "SupName", supProducts.SupId);
            return View(supProducts);
        }

        // POST: SupProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,ProductName,UnitPrice," +
            "EventId,SupId,CreatedBy,CreatedAt,UpdatedBy,UpdatedAt")] SupProducts supProducts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supProducts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EventId = new SelectList(db.Celebrations,
                "EventId", "EventName", supProducts.EventId);
            ViewBag.SupId = new SelectList(db.Suppliers, "SupId", 
                "SupName", supProducts.SupId);
            return View(supProducts);
        }

        // GET: SupProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupProducts supProducts = db.SupProducts.Find(id);
            if (supProducts == null)
            {
                return HttpNotFound();
            }
            return View(supProducts);
        }

        // POST: SupProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SupProducts supProducts = db.SupProducts.Find(id);
            db.SupProducts.Remove(supProducts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PMWelfare/Views/SupProducts/Create.cshtml
@model PMWelfare.Models.SupProducts

@{
    ViewBag.Title = "Create";
}
<div>
    <ol class="breadcrumb">
        <li> @Html.ActionLink("Home", "Index", "Home")</li>
        <li> @Html.ActionLink("Suppliers' Products", "Index")</li>
        <li class="active"> @Html.ActionLink("Add New Product", "Create")</li>
    </ol>
</div>
<h2 style="text-align:center">Create A New Product</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventId, "EventId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EventId", null, htmlAttributes: new { @class = "form-control",id = "DropDown" })
                @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SupId, "SupId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupId, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $("#DropDown").chosen();
        })
    </script>
}

PMWelfare/Views/SupProducts/Delete.cshtml
@model PMWelfare.Models.SupProducts

@{
    ViewBag.Title = "Delete";
}
<div>
    <ol class="breadcrumb">
        <li> @Html.ActionLink("Home", "Index", "Home")</li>
        <li> @Html.ActionLink("Suppliers' Products", "Index", "SupProduct")</li>
        <li class="active"> @Html.ActionLink("Remove Product", "Delete")</li>
    </ol>
</div>
<h2>Delete Record</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SupProducts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Celebration.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celebration.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.SupTel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.SupTel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PMWelfare/Views/SupProducts/Details.cshtml
@model PMWelfare.Models.SupProducts

@{
    ViewBag.Title = "Details";
}
<div>
    <ol class="breadcrumb">
        <li> @Html.ActionLink("Home", "Index", "Home")</li>
        <li> @Html.ActionLink("Suppliers' Products", "Index","SupProducts")</li>
        <li class="active"> @Html.ActionLink("Details Of The Product", "Create")</li>
    </ol>
</div>
<h2>Details of @Model.ProductName  </h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Celebration.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celebration.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.SupTel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.SupTel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductId }) 
</p>

PMWelfare/Views/SupProducts/Edit.cshtml
@model PMWelfare.Models.SupProducts

@{
    ViewBag.Title = "Edit";
}
<div>
    <ol class="breadcrumb">
        <li> @Html.ActionLink("Home", "Index", "Home")</li>
        <li> @Html.ActionLink("Suppliers' Products", "Index")</li>
        <li class="active"> @Html.ActionLink("Edit Product", "Edit")</li>
    </ol>
</div>
<h2 style="text-align:center    ">Edit The Record for @Model.ProductName</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventId, "EventId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EventId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SupId, "SupId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

PMWelfare/Views/SupProducts/Index.cshtml
@model IEnumerable<PMWelfare.Models.SupProducts>

@{
    ViewBag.Title = "Products supplied";
}
<div>
    <ol class="breadcrumb">
        <li> @Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active"> @Html.ActionLink("Suppliers' Products", "Index")</li>

    </ol>
</div>
<h2 style="text-align:center">List of Products supplied</h2>
<br />
<p>
    <button class=" btn btn-info" onclick="location.href='@Url.Action("Create","SupProducts")'">
        Add New Product
    </button>

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Celebration.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supplier.SupTel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem =>  item.Celebration.EventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier.SupTel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice )
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductId }) 
            </td>
    </tr>
}

</table>